version: '3.8'

services:
  bot:
    build: .
    container_name: super_link_share_bot
    restart: always
    env_file:
      - .env
    environment:
      - API_ID=${API_ID}
      - API_HASH=${API_HASH}
      - BOT_TOKEN=${BOT_TOKEN}
      - MONGO_DB_URI=${MONGO_DB_URI}
      - DB_NAME=${DB_NAME}
      - OWNER_ID=${OWNER_ID}
      - ADMINS=${ADMINS}
      - FSUB_ENABLED=${FSUB_ENABLED}
      - LOG_CHANNEL=${LOG_CHANNEL}
      - PORT=${PORT}
